version: '3'
services:
  cooking:
    image: mediawiki:1.40.1
    restart: always
    ports:
      - 8080:80
    links:
      - db
    volumes:
      - images:/var/www/html/images
      - ./LocalSettings.php:/var/www/html/LocalSettings.php
      - ./logo.png:/var/www/html/resources/assets/logo.png
      - ./favicon.ico:/var/www/html/favicon.ico
  db:
    image: mariadb:11.2.2
    restart: always
    volumes:
      - db:/var/lib/mysql
    env_file: db.env

volumes:
  images:
  db:
